version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/circleci-working-directory # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory
      
      - run: mvn clean install # run 
      
      - store_artifacts: # store the war as an artifact
          path: irongatewaycontroller/target/irongatewaycontroller-1.0-SNAPSHOT.war

  Run Test: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/circleci-working-directory # directory where steps will run
    
    steps: # a collection of executable commands
	- run: echo "Run Api test" 
     

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - Run Test
    	requires:
	  - build
