version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/circleci-working-directory # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers 

    steps: # a collection of executable commands

      - checkout # check out source code to working directory
      
      - run: mvn clean install # run 
      
      - store_artifacts: # store the war as an artifact
          path: irongatewaycontroller/target/irongatewaycontroller-1.0-SNAPSHOT.war

  Deploy: 
    
    working_directory: ~/circleci-working-directory 

    docker:

      - image: circleci/node:4.8.2

    steps: 
      - run: echo "Run Api Test"

  Employer Api Test: 
    
    working_directory: ~/circleci-working-directory 

    docker:

      - image: circleci/node:4.8.2

    steps: 
      - run: echo "Employer Api Test"

  Job Seeker Api Test: 
    
    working_directory: ~/circleci-working-directory 

    docker:

      - image: circleci/node:4.8.2

    steps: 
      - run: echo "Job Seeker Api Test"

  Deploy to Staging: 
    
    working_directory: ~/circleci-working-directory 

    docker:

      - image: circleci/node:4.8.2

    steps: 
      - run: echo "Deploy to Staging"

workflows:
  version: 2
  development_workflow:
    jobs:
      - build
      - Deploy
          requires:
            - build
      - Employer Api Test
          requires:
            - Deploy
      - Job Seeker Api Test
          requires:
            - Deploy
      - Deploy to Staging
          requires:
            - Employer Api Test
            - Job Seeker Api Test

